# Generated by Django 5.1.3 on 2024-12-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('dni', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
